# Web that want to crawls (only support vnexpress now)
# webname: "vnexpress"
webname: "vietnamnet"

# tasks = ["url", "type"]
task: "type"

#logger config file path
logger_fpath: "logger/logger_config.yml"
urls_fpath: "urls.txt"
output_dpath: "result"
num_workers: 1

# if task == "type": 
# article_type == "all" to crawl all of types
article_type: "all"
total_pages: 3